FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app

COPY . .
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY --from=build /out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "ReadmeServer.dll"]
